### ISSUE TITLE
Publish document when workflow is completed

### ISSUE THREAD

**Issue by guidogambini1995** [sanity-io/sanity-plugin-workflow#35]
Hi! I have been failing trying to get the way of publishing the documents after pressing complete button in the 'approved' column status.

![Captura de pantalla 2023-06-15 a las 16 12 42](https://github.com/sanity-io/sanity-plugin-workflow/assets/132886578/082f6c89-9278-4a2c-8dc6-743b3cdf3f3a)

Is there any way to publish automatically the document by clicking 'complete' and removing it from the workflow?

**Comment by andresclua** [comment]
hey @SimeonGriggs any updates on this?
