### ISSUE TITLE
Add a custom button when documents are in 'in review' and 'changes requested'

### ISSUE THREAD

**Issue by guidogambini1995** [sanity-io/sanity-plugin-workflow#36]
Hello! Is it possible to add a custom button in the document structure during its workflow through 'in review' and 'changes requested' columns?

<img width="502" alt="Captura de pantalla 2023-06-15 a la(s) 16 42 36" src="https://github.com/sanity-io/sanity-plugin-workflow/assets/132886578/86c1babd-f4ad-44a3-a441-6aa14c8c58ae">

**Comment by andresclua** [comment]
hey @SimeonGriggs any updates on this?

**Comment by SimeonGriggs** [comment]
Not possible unfortunately.

As stated in the plugin readme:

> This plugin is distributed as an example implementation of customization APIs in the Sanity Studio V3 ... It is meant as a starting point intended to be forked and customized to the needs of your organization and content creators
